def Text(i,k,text):

	subsetArr = []
	for letter in range(i,i+k):
		subsetArr.append(text[letter])
	subset = str(''.join(subsetArr))
	return subset

#print(Text(4,3,"GACCATACTG"))

#------------------------------------------------------

def PatternCount(text, pattern):
	count = 0
	for i in range(len(text)-len(pattern)+1):
		window = Text(i, len(pattern), text)
		if window  == pattern:
			count = count+1
	return count

print(PatternCount("CGCCAAGCCTGAATTATTTGACAGCCTGAAGCCTGAATGCCTGAACATATTGCCTGAATGCCTGAAACATGCCTGAACAGCCTGAAGCCTGAAGCCTGAACCGCCTGAAGCCTGAAGCCTGAATGTGCCTGAAAAGCGGCCTGAATGCCTGAACAGCGCCTGAATTGGTCCAAATGGCCTGAACCGCCTGAATAGGGCCTGAACAAGGCCTGAACGCCTGAACGCCTGAAGCCTGAATGCCTGAAGCCTGAACGCCTGAAGCCTGAAAGCCTGAATTTGTGCCTGAACCGGCCCGAGCCTGAACGCCTGAAAGCCTGAAAGCCTGAAATGCAGGACAGGCCTGAACCTCCTAAGGTCACAGGGGCCTGAAAGCCTGAAAGCCTGAAGCCTGAAGCCTGAAGCCTGAAACTGCCTGAAAGCCTGAACCGCCTGAATGGCCTGAAAGGCCTGAAAGCCTGAAGCCTGAAAAGCCTGAACTATTCGGCCTGAAGGATGCCTGAAGCCTGAATCGGCCTGAATGGTGCCTGAAGCCTGAAGCCTGAAAAGAAGCCTGAAGCCTGAAGCCTGAACCGCCTGAATACCGCCTGAATGCCTGAAAGACCGCCTGAAGGTTAGGGCCTGAATGTTTAGCCTGAAGACGGCAAGCCTGAAAGCCTGAACTTGTGGCCTGAATGCCTGAAGCCTGAACATGCCTGAAGCCTGAAACGCCTGAAGCCTGAATATGCCTGAATAGCCTGAAGGCCTGAAAAGTAAGCCTGAAGCCTGAACCGCCTGAATCGCCTGAAGCCTGAACGCCTGAAGCCTGAAGTTATCGGCCTGAACGTGCCTGAAACAAACGCCTGAACCGTGCCTGAATCGGCCTGAAGCCTGAATGCCTGAACTCTAGAGCTGGCATCGCCTGAAGCCTGAAGGCCTGAAATGGCCTGAAGCCTGAACAGGCGAATTCGCGCCGCCTGAAAGGCCTGAACTAGCCTGAAGCCTGAA","GCCTGAAGC"))
